services:
  mysql:
    image: postgres
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123
      - POSTGRES_DATABASE=mydb
      - POSTGRES_ROOT_PASSWORD=123